name: Backend CICD
on:
  push:
    branches:
      - deployment
    paths:
      - "backend/**"
      - ".github/workflows/backend.yml"

permissions:
  packages: write

jobs:
  backend-deploy:
    name: Backend CICD
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Login to GHCR
        run: |
          echo "${{ secrets.PAT_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Build the backend image and push it to GHCR
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/monolythicbc-backend:latest
          context: backend

      - name: Deploy to AWS instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_INSTANCE_IP }}
          username: ${{ secrets.AWS_INSTANCE_USERNAME }}
          key: ${{ secrets.AWS_INSTANCE_PRIVATE_KEY }}
          script: |
            sudo docker stop monolythicbc-backend || true

            sudo docker rm monolythicbc-backend || true 

            echo "${{ secrets.PAT_TOKEN }}" | sudo docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

            sudo docker pull ghcr.io/${{ github.repository_owner }}/monolythicbc-backend:latest
            sudo docker run -d -p 8080:80 --name monolythicbc-backend ghcr.io/${{ github.repository_owner }}/monolythicbc-backend:latest
