name: Backend CICD
run-name: Backend deployment update triggered by ${{ github.actor }}.

on:
  push:
    branches:
      - deployment
    paths:
      - "backend/**"
      - ".github/workflows/backend.yml"

jobs:
  backend-deploy:
    name: Backend CICD
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Login to GHCR
        run: |
          echo "${{ secrets.PAT_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Build the backend image and push it to GHCR
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/monolythicbc-backend:${{ github.sha }}
          context: backend

      - name: Set permissions for private key
        run: |
          echo "${{ secrets.AWS_PRIVATE_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Deploy to AWS instance
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.AWS_INSTANCE_USERNAME }}@${{ ssecrets.AWS_INSTANCE_IP }} '

            echo "${{ secrets.PAT_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
            
            docker pull ghcr.io/${{ github.repository_owner}}/monolythicbc-backend:${{ github.sha }} &&

            docker stop monolythicbc-backend || true &&
            
            docker rm monolythicbc-backend || true &&
            
            docker run -d --name monolythicbc-backend -p 80:80 ghcr.io/${{ github.repository_owner}}/monolythicbc-backend:${{ github.sha }}
          '
